accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

answers/urls.py
from django.urls import path

app_name = "answers"

urlpatterns = [
]

questions/urls.py
from django.urls import path

from . import views

app_name = "questions"

urlpatterns = [
    path('', views.question_list, name='question_list'),
    path('create_question/', views.create_question, name="create_question"),
    path('<pk>/', views.question_detail, name='question_detail'),
    path('edit_question/<pk>', views.edit_question, name="edit_question"),
    path('delete/<pk>', views.delete_question, name="delete_question"),
]

stackoverflow_clone/urls.py
from django.contrib import admin
from django.urls import path, include
from questions import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.question_list),
    path('questions/', include('questions.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

answers/models.py
from django.db import models
from django.contrib.auth.models import User
from questions.models import Question


class Answer(models.Model):
    answer_text = models.TextField()
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.answer_text

    class Meta:
        ordering = ["-created_at"]
        managed = True
        verbose_name = 'Answer'
        verbose_name_plural = 'Answers'

questions/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField

# Create your models here.
class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, default="", null=True)
    tags = ArrayField(models.CharField(max_length=255, unique=False,
                            blank=True), unique=False, blank=True,
                            default=list)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ["-created_at", "-updated_at"]

    def __str__(self):
        return self.title

answers/forms.py
from django import forms
from . import models


class AnswerForm(forms.ModelForm):
    answer_text = forms.Textarea()
    answer_text.widget = forms.Textarea(
        attrs={
            'class': "form-control",
            'rows': 4,
            'placeholder': "Give answer here!"
        }
    )

    class Meta:
        model = models.Answer
        fields = [
            'answer_text',
        ]

questions/forms.py
from django import forms
from . import models

class QuestionForm(forms.ModelForm):
    class Meta:
        model = models.Question
        fields = [
            'title', 'body', 'tags'
        ]

stackoverflow_clone/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from stackoverflow_clone.forms import SignUpForm
from django.urls import reverse_lazy
from django.views import generic

# Create your views here.
class SignUp(generic.CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

answers/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from . import models, forms
from django.http import HttpResponseRedirect
from questions.models import Question


def answer_list(request, question_pk):
    answers = get_object_or_404(models.Answer, question_pk=question_pk)
    return render(request, 'questions/question_detail.html', {'answers': answers})


@login_required
def create_answer(request, question_pk):
    form = forms.AnswerForm()
    question = get_object_or_404(Question, pk=question_pk)
    if request.method == "POST":
        form = forms.AnswerForm(request.POST)
        if form.is_valid:
            answer = form.save(commit=False)
            answer.author = request.user
            answer.question = question
            answer.save()
            messages.success(request, "Question created successfully")
            return HttpResponseRedirect(reverse_lazy('questions:question_detail', kwargs={'pk': question.pk}))
    return render(request, 'questions/question_form.html', {'form': form})

questions/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from . import models, forms
from django.http import HttpResponseRedirect


def question_list(request):
    questions = models.Question.objects.all()
    return render(request, 'questions/question_list.html', {'questions': questions})


def question_detail(request, pk):
    question = get_object_or_404(models.Question, pk=pk)
    return render(request, 'questions/question_detail.html', {
        'question': question,
    })


@login_required
def create_question(request):
    form = forms.QuestionForm()
    if request.method == "POST":
        form = forms.QuestionForm(request.POST)
        if form.is_valid:
            question = form.save(commit=False)
            question.author = request.user
            question.save()
            messages.success(request, "Question created successfully")
            return HttpResponseRedirect(reverse_lazy('questions:question_detail', kwargs={'pk': question.pk}))
    return render(request, 'questions/question_form.html', {'form': form})


@login_required
def edit_question(request, pk):
    question = get_object_or_404(models.Question, pk=pk)
    form_class = forms.QuestionForm
    form = form_class(instance=question)
    if request.method == "POST":
        form = form_class(request.POST, instance=question)
        if form.is_valid:
            form.save()
            messages.success(request, "Question updated successfully")
            return HttpResponseRedirect(reverse_lazy('questions:question_detail', kwargs={'pk': question.pk}))
    return render(request, 'questions/question_form.html', {
        'form': form,
        'question': question
    })


@login_required
def delete_question(request, pk):
    question = get_object_or_404(models.Question, pk=pk)
    question.delete()
    messages.success(request, "Question deleted")
    return HttpResponseRedirect(reverse_lazy('questions:question_list'))

answers/templates/answers/answer-form.html
<!-- {% block answer %} -->
<div class="modal col-sm-9 col-md-7 col-lg-9 mx-auto" id="answer-form">
    {{ block.super }}
  <div class="modal-dialog card card-signin my-5 border-info flex-row">
    <div class="modal-content card-body">
      <div class="modal-body">
      <form method="post" validate>
        {% csrf_token %}
        <div class="form-group">
          <span class="helptext text-danger"> {{ field.errors }} </span>
          <input type="text" class="form-control"%>
        </div>

        <button
        type="submit"
        class="btn btn-outline-info text-uppercase font-weight-bold"
        method="POST"
        >
          Submit Answer
        </button>
      </form>
      </div>
    </div>
  </div>
</div>
<!-- {% endblock answer %} -->

questions/templates/questions/question_detail.html
{% extends "layout.html" %}
{% load widget_tweaks %}
{% load question_extras %}

{% block title %} {{ question.title }} {% endblock title %}

{% block content %}

<div>
    {{ block.super }}
    <br>
    <article>
        <h2 class="text-info">{{ question.title }}</h2>
        <ul class="nav nav-tabs" >

          {% if user.is_authenticated %}
              <hr>
              <li class="nav-item">
                  <a class="nav-link active bg-info text-white" href="{% url 'questions:create_question' %}">Ask a Question</a>
                </li>
              {% endif %}
              {% if user == question.author %}
                <li class="nav-item">
                  <a class="nav-link active bg-info text-white" href="{% url 'questions:edit_question' pk=question.pk %}">Edit Question</a>
                </li>
          {% endif %}

        </ul>
        <div class="callout secondary">
            {{ question.body|markdown_to_html }}
        </div>
    </article>
{#    <ul class="nav nav-tabs" >#}
{##}
{#      {% if user.is_authenticated %}#}
{#      <hr>#}
{#      <li class="nav-item">#}
{#          <a class="nav-link active bg-info text-white" href="{% url 'questions:create_question' %}">Ask a Question</a>#}
{#        </li>#}
{#      {% endif %}#}
{#      {% if user == question.author %}#}
{#        <li class="nav-item">#}
{#          <a class="nav-link active bg-info text-white" href="{% url 'questions:edit_question' pk=question.pk %}">Edit Question</a>#}
{#        </li>#}
{#    {% endif %}#}
{##}
{#    </ul>#}
</div>
  
{% endblock content %}

questions/templates/questions/question_form.html
{% extends "layout.html" %}
{% load widget_tweaks %}

{% block title %}
    {{ form.instance.title | default:"New Question"}} | {{ question.title }} {{ block.super }}
{% endblock title %}

{% block content %}
<!-- {% if perms.app_label.can_do_something %} -->

<!-- {% endif %} -->
<div class="col-sm-9 col-md-7 col-lg-9 mx-auto">
    {{ block.super }}
  <div class="card card-signin my-5 border-info flex-row">
    <div class="card-body">
      <h2 class="card-title text-center text-info">
          {{ form.instance.title | default:"Make a new question"}}</h2>

      {% if user.is_authenticated %}
      <form method="post" validate>
        {% csrf_token %} 
        {% for field in form %}
        <div class="form-group">
          <span class="helptext text-danger"> {{ field.errors }} </span>
          {{ field.label_tag }}
          {% render_field field class="form-control"%}
        {% endfor %}
        </div>
        <button
        type="submit"
        class="btn btn-outline-info text-uppercase font-weight-bold"
        method="POST"
        >
         Save
        </button>
        {% if form.instance.title %}
        <a href="{% url 'questions:delete_question' pk=question.pk %}" 
          class="btn btn-outline-info float-right text-uppercase text-danger font-weight-bold">
          Delete</a>
        {% else %}
        <a href="{% url 'questions:question_list' %}" 
          class="btn btn-outline-info float-right text-uppercase text-danger font-weight-bold">
          Cancel</a>
        {% endif %}
      </form>
      {% endif %}

    </div>
  </div>
</div>
  
{% endblock content %}

questions/templates/questions/question_list.html
{% extends "layout.html" %}
{% load widget_tweaks %}

{% block title %}
All Questions {{ block.super }}
{% endblock title %}

{% block content %}
{{ block.super }}

{%  for question in questions %}
<br>
<div class="card my-6 border-info">
    <div class="card-body">
        <div>
            <div class="text-secondary text-right">By: {{ question.author }} 
                    - {{ question.created_at|date:"j F, Y" }}</div>
            <a class="text-info card-title responsive-font-size h5" 
            href="{% url 'questions:question_detail' pk=question.pk%}">
            {{ question.title }}</a>

        <hr>
        {% if question.body|wordcount <= 30 %}
        <p class="card-text">{{ question.body }}</p>
        {% else %}
            {{ question.body|truncatewords:30 }}
            <a href="{% url 'questions:question_detail' pk=question.pk %}" class="card-link">Read More</a>
        {% endif %}
    </div>
    </div>
</div>
{% endfor %}

{% endblock content %}

templates/layout.html
<!DOCTYPE html>
{% load widget_tweaks %}
{% load static from staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    {% block css %}{% endblock %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
    {% if user.is_authenticated %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <a class="navbar-brand" href="{% url 'questions:question_list' %}">
            <img src="https://cdn.freebiesupply.com/logos/large/2x/stackoverflow-com-logo-png-transparent.png" 
            alt="Home" style="width:38px;height:33px;"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
        <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link " href="{% url 'questions:question_list' %}">Home </a>
        </li>
        <li class="nav-item">
                <a class="nav-link" href="{% url 'questions:create_question' %}">Ask a Question</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ user.username }}
            </a>
            <div class="dropdown-menu bg-info" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Profile</a>
            <a class="dropdown-item" href="{% url 'logout' %}"><span class="fas fa-sign-in-alt"></span> Logout</a>
            </div>
        </li>
        </ul>
    </div>
    </nav>
    {% else %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
        <a class="navbar-brand" href="{% url 'questions:question_list' %}">
            <img src="https://cdn.freebiesupply.com/logos/large/2x/stackoverflow-com-logo-png-transparent.png" 
            alt="Home" style="width:38px;height:33px;"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signup' %}"><span class="fas fa-user"></span> Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}"><span class="fas fa-sign-in-alt"></span> Login</a>
                </li>
            </ul>
        </div>
    </nav>

    {% endif %}
    <div>
        {% if messages %}
            {% for message in messages %}
            <div data-alert class="alert alert-info alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
               <strong> {{ message }} </strong>
            </div>
            {% endfor %}
        {% endif %}

        {% block content %}{% endblock %}
    </div>
    <footer class="footer">
        <hr/>
        <div>
            <p>&copy; Stackoverflow Clone by &copy; Tomusange Henry</p>
        </div>
    </footer>
</div>
</body>
</html>